
POST http://localhost:80/api/class
Content-Type: application/json

{
  "class_name": "Pilates",
  "start_date": "2021-04-01",
  "end_date": "2021-04-10",
  "capacity": "20"
}

###

POST http://localhost:80/api/bookings
Content-Type: application/json

{
  "username": "john_doe",
  "date": "2021-04-01"
}

###
