POST http://glofox.local/api/say/1/hello
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

anooz
--WebAppBoundary--
Content-Disposition: form-data; name="start_date"

2020-01-02
--WebAppBoundary--
Content-Disposition: form-data; name="end_date"

2020-01-20
--WebAppBoundary--
Content-Disposition: form-data; name="capacity"

20
--WebAppBoundary--

###
